### ISSUE TITLE
Create script that does the package installations

### ISSUE THREAD

**Issue by HokieGeek** [HokieGeek/distro-config#17]
Decisions to make:
File format: json vs yaml
File parser: python vs go

**Comment by HokieGeek** [comment]
# Format

## json

``` json
{
    "groups": {
        "group": {
            "id": "0",
            "name": "NAME OF GROUP",
            "enabled": true,
            "installer": "yaourt",
            "packages": ["pkg1", "pkg2", "pkgN"]
        }
    }
}
```

## Yaml

``` yaml
groups:
    group:
        id: 0
        name: NAME OF GROUP
        enabled: true
        installer: yaourt
        packages:
            - pkg1
            - pkg2
            - pkgN
```
